# Generated by Django 3.0.4 on 2020-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='name')),
                ('surname', models.CharField(max_length=36, verbose_name='surname')),
                ('city', models.CharField(max_length=36, verbose_name='city')),
                ('rented_rooms', models.IntegerField(verbose_name='rented_rooms_count')),
            ],
        ),
    ]
