# Generated by Django 3.0.5 on 2020-05-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0002_auto_20200330_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('house_number', models.PositiveIntegerField(max_length=50, verbose_name='house number')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_area', models.PositiveIntegerField(max_length=5, verbose_name='room area')),
                ('basement_area', models.PositiveIntegerField(max_length=5, verbose_name='basement area')),
                ('basement_ratio', models.PositiveSmallIntegerField(max_length=1, verbose_name='basement ratio')),
                ('KT', models.PositiveSmallIntegerField(max_length=1, verbose_name='KT')),
                ('address', models.ManyToManyField(to='RentCheck.Address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'Таблица помещений',
                'verbose_name_plural': 'Таблица помещений',
            },
        ),
        migrations.DeleteModel(
            name='table',
        ),
    ]
