# Generated by Django 3.0.5 on 2020-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0003_auto_20200515_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some name', max_length=50, verbose_name='name')),
                ('surname', models.CharField(default='some surname', max_length=50, verbose_name='surname')),
                ('city', models.CharField(default='some city', max_length=50, verbose_name='city')),
                ('rented_rooms_count', models.PositiveIntegerField(default=0, verbose_name='rented rooms count')),
            ],
            options={
                'verbose_name': 'Таблица арендаторов',
                'verbose_name_plural': 'Таблица арендаторов',
            },
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='address',
        ),
        migrations.AddField(
            model_name='rooms',
            name='city',
            field=models.CharField(default='some city', max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='country',
            field=models.CharField(default='some country', max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='house_number',
            field=models.PositiveIntegerField(default=0, verbose_name='house number'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='street',
            field=models.CharField(default='some street', max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='KT',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='KT'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='basement_area',
            field=models.PositiveIntegerField(default=0, verbose_name='basement area'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='basement_ratio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='basement ratio'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_area',
            field=models.PositiveIntegerField(default=0, verbose_name='room area'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='tenant',
            name='rented_room',
            field=models.ManyToManyField(to='RentCheck.Rooms', verbose_name='rented room'),
        ),
    ]
