# Generated by Django 3.0.5 on 2020-05-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0004_auto_20200515_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
