# Generated by Django 3.0.5 on 2020-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0005_delete_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some name', max_length=50, verbose_name='name')),
                ('surname', models.CharField(default='some surname', max_length=50, verbose_name='surname')),
                ('middle_name', models.CharField(default='some surname', max_length=50, verbose_name='surname')),
                ('rented_rooms_count', models.PositiveIntegerField(default=0, verbose_name='rented rooms count')),
                ('rented_room', models.ManyToManyField(to='RentCheck.Rooms', verbose_name='rented room')),
            ],
            options={
                'verbose_name': 'Таблица арендаторов',
                'verbose_name_plural': 'Таблица арендаторов',
            },
        ),
    ]
