# Generated by Django 3.0.5 on 2020-05-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0006_auto_20200518_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='country'),
        ),
    ]
