# Generated by Django 3.0.5 on 2020-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0007_auto_20200518_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='street',
            field=models.CharField(default='', max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='middle_name',
            field=models.CharField(default='', max_length=50, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rented_rooms_count',
            field=models.PositiveIntegerField(verbose_name='rented rooms count'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='surname'),
        ),
    ]
