# Generated by Django 3.0.5 on 2020-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0008_auto_20200518_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='KT',
            field=models.PositiveSmallIntegerField(verbose_name='KT'),
        ),
    ]
