# Generated by Django 3.0.5 on 2020-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0009_auto_20200518_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='basement_area',
            field=models.PositiveIntegerField(verbose_name='basement area'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='basement_ratio',
            field=models.PositiveSmallIntegerField(verbose_name='basement ratio'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='house_number',
            field=models.PositiveIntegerField(verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_area',
            field=models.PositiveIntegerField(verbose_name='room area'),
        ),
    ]
