# Generated by Django 3.0.5 on 2020-05-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0010_auto_20200518_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='street',
            field=models.CharField(max_length=50, verbose_name='street'),
        ),
    ]
