# Generated by Django 3.0.6 on 2020-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0011_auto_20200518_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='author_id',
            field=models.IntegerField(default=0, verbose_name='author name'),
        ),
    ]
