# Generated by Django 3.0.6 on 2020-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0012_rooms_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='author_id',
            field=models.PositiveIntegerField(verbose_name='author name'),
        ),
    ]
