# Generated by Django 3.0.6 on 2020-05-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCheck', '0013_auto_20200524_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='tenant_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tenant email'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='author_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='author name'),
        ),
    ]
